Fix compiler warning in test case
From CI:

build/regression/issue_1017/test.c: In function ‘stream_callback’:
build/regression/issue_1017/test.c:26:6: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   26 |     *(uintptr_t *)(&stream->state) = (uintptr_t)cursor;